# Generated by Django 3.2 on 2021-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalservice',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
