# Generated by Django 3.2 on 2021-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('_is_published_landing', models.BooleanField(default=False, verbose_name='Новость опубликована на главной странице')),
            ],
            options={
                'verbose_name': 'Вопрос Ответ',
                'verbose_name_plural': 'Вопросы и Ответы',
                'ordering': ['-date_created'],
            },
        ),
    ]
