# Generated by Django 3.2 on 2021-04-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_questionanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='_is_published_landing',
            new_name='is_published_landing',
        ),
    ]
