# Generated by Django 3.2 on 2021-05-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='is_published_landing',
            field=models.BooleanField(default=False, verbose_name='Опубликовано на главной странице'),
        ),
    ]
